### ISSUE TITLE
Formatting fsx files add module declaration

### ISSUE THREAD

**Issue by naveensrinivasan** [dungpa/fantomas#191]
I am trying to format my fsx file in osx using fantomas. It adds a module declaration to the fsx file. Is this an intended behavior. 

``mono Fantomas.exe --stdout`` https://github.com/naveensrinivasan/adventcode/blob/master/2.fsx 

The sample fsx is the one I have referenced above.

Here is the formatted source code after running through 
```fsharp
module ``2``

open System
open System.IO

type Rect = 
    { Length : int
      Width : int
      Height : int }

let parse (s : string) = 
    let splitstring = s.Split([| 'x' |])
    { Length = int splitstring.[0]
      Width = int splitstring.[1]
      Height = int splitstring.[2] }

let prismarea (r : Rect) = 
    let calculations = 
        [ (2 * r.Length * r.Width)
          (2 * r.Width * r.Height)
          (2 * r.Height * r.Length) ]
    
    let lowest = (calculations |> List.min) / 2
    lowest :: calculations |> List.reduce (+)

let area = parse >> prismarea

let totalarea = 
    File.ReadAllLines(Path.Combine(__SOURCE_DIRECTORY__, "2.txt"))
    |> Seq.map (fun f -> area f)
    |> Seq.reduce (+)

printfn "Total area required is %i" totalarea

let ribbonLength (r : Rect) = 
    let list = [| r.Height; r.Width; r.Length |]
    let bow = list |> Array.reduce (*)
    let [| l; w |] = Array.sort (list).[0..1]
    let wrap = (l + l) + (w + w)
    bow + wrap

let ribbonsize = parse >> ribbonLength

let totalRibbonLength = 
    File.ReadAllLines(Path.Combine(__SOURCE_DIRECTORY__, "2.txt"))
    |> Seq.map (fun f -> ribbonsize f)
    |> Seq.reduce (+)

printfn "Total Ribbon length required is %i " totalRibbonLength

```

Thanks

**Comment by OkayX6** [comment]
Note that this only reproduces when formatting the whole document, not the selection.

**Comment by dungpa** [comment]
@OkayX6 The culprit is at https://github.com/dungpa/fantomas/blob/839f3851934aee38a926b69901bdc8ac427e1455/src/Fantomas/CodePrinter.fs#L82-L83

In formatting selection, we choose the file name i.e. `tmp.fs`, which always works. During formatting document, we pass file names but don't check them properly. File names should be injected to AST context and used in some way https://github.com/dungpa/fantomas/blob/839f3851934aee38a926b69901bdc8ac427e1455/src/Fantomas/CodePrinter.fs#L13-L31.
